### ISSUE TITLE
Update docs for SSDynamicButton

### ISSUE THREAD

**Issue by Grubas7** [splinesoft/SSDynamicText#10]
Github readme:
Add UIButton:
![screen shot 2015-07-20 at 20 14 11 1](https://cloud.githubusercontent.com/assets/9446070/8783424/06fdddc8-2f1c-11e5-852e-f65aa24a4655.png)

There's no button example, yet:
![screen shot 2015-07-20 at 20 14 40](https://cloud.githubusercontent.com/assets/9446070/8783438/203d3036-2f1c-11e5-8d20-b27d0ed1445e.png)

labelWithFont -> buttonWithFont
![screen shot 2015-07-20 at 19 45 29](https://cloud.githubusercontent.com/assets/9446070/8782773/f4aa8cd8-2f17-11e5-982d-2353c8d552ee.png)

Cocoapods.org:
Add Button
![screen shot 2015-07-20 at 19 47 04](https://cloud.githubusercontent.com/assets/9446070/8782824/3834676c-2f18-11e5-82bd-b6521c6cc205.png)

**Comment by Grubas7** [comment]
Change only repository description, and this issue will be ready to close :)

**Comment by jhersh** [comment]
:+1:
