### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by Grubas7** [splinesoft/SSDynamicText#30]
We are using last SSDynamicText few months and we didn't notice any `SSDynamicText` related crashes. Maybe it's time to release version 1.0?
@jhersh what do you think?

**Comment by jhersh** [comment]
Sure thing, feel free to do a release.

**Comment by Grubas7** [comment]
@jhersh This took me a while, but ready for review ;)

**Comment by Grubas7** [comment]
@jhersh could you upload new podspec to cocoapods.org?

**Comment by Grubas7** [comment]
@segiddins Thanks 🎉
