### ISSUE TITLE
Manually set preferred size

### ISSUE THREAD

**Issue by kengleong** [splinesoft/SSDynamicText#33]
Nice library! 

Is it possible to change the text ''preferred size" manually. Doesn't mean changing the system preferred size but perhaps a separate attribute so that user can change the size of font in that particular app instead of changing the entire system font size

**Comment by jhersh** [comment]
You can make your own slider with your own preferred size delta. Whenever you create an SSDynamicText view, add your custom delta to the base size you pass in at initialize time.
