### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Grubas7** [splinesoft/SSDynamicText#40]
Folks from company noticed memory problem in `SSDynamicText`. They was looking for potential strong retain cycles in other code, but they found leks in `SSDynamicLabel`.

I build app to check the problem, and there is leak even in the simplest code:
![screen shot 2016-11-12 at 14 13 25](https://cloud.githubusercontent.com/assets/9446070/20238186/c17d1f26-a8e5-11e6-85f9-abb8d0828b00.png)

Looks like the problem is caused by strong retain cycle of `super`:
```
changer.fontChangeBlock = ^(UIFont *font) {
    [super setFont:font];
};
```

Same code appears in `SSDynamicTextView` and `SSDynamicTextField` classes, so I assume there is the same retain cycle.

Simple app in attachment:
[SSDynamicLeak.zip](https://github.com/splinesoft/SSDynamicText/files/587225/SSDynamicLeak.zip)

**Comment by Grubas7** [comment]
@segiddins @jhersh Could you release version 1.1.1 and upload to cocoapods?

**Comment by Grubas7** [comment]
@segiddins Any change to release 1.1.1? I don't have permissions to public podspec on cocoapods repo.

**Comment by segiddins** [comment]
I'm on vacation now, I'll try to remember when I got home

**Comment by Grubas7** [comment]
@segiddins Sorry for being such a pain, but is this a good time for release?

**Comment by segiddins** [comment]
@Grubas7 I'll do my best
