### ISSUE TITLE
`-setup` called twice after `-init`

### ISSUE THREAD

**Issue by Grubas7** [splinesoft/SSDynamicText#6]
`-initWithFrame:` method is Designated Initializer for UIView. UILabel, UITextView, UITextField are classes inheriting from UIView, so after code
```
[[SSDynamicLabel alloc] init];
```
first will be called method `-init` then `-initWithFrame:`, so method `-setup` is called twice.
To fix this, just remove `-init` override from all UIView inheriting classes.

**Comment by jhersh** [comment]
Good catch @Grubas7!

**Comment by Grubas7** [comment]
@jhersh Could you update podfile also on cocoapods.org?
Thanks in advance!

**Comment by jhersh** [comment]
@Grubas7 done and done!
