### ISSUE TITLE
Make class method inheritable.

### ISSUE THREAD

**Issue by Grubas7** [splinesoft/SSDynamicText#7]
I wanted to create subclass of SSDynamicLabel and provide margins to her.
eg:
```
@interface PaddedDynamicLabel : SSDynamicLabel
@property (nonatomic, assign) UIEdgeInstets paddingInsets
@end
```
But when I use my class:
```
PaddedDynamicLabel *label = [PaddedDynamicLabel labelWithFontDescriptor:fontDescriptor];
label.paddingsInsets = UIEdgeInsetsMake(0.0f, 8.0f, 0.0f, 8.0f);
```
I get crash ;(

The problem is initialization of objects in class methods:
`SSDynamicLabel *label = [SSDynamicLabel new];`
which could be easily fix by:
`SSDynamicLabel *label = [[self class] new];` 
([self new] will work also)

**Comment by jhersh** [comment]
Another good catch! This code is really old, it needs the help :)
